# All paths used in the project are defined in this file

import os
from constants import *

# Dataset to be used

DATASET_NAME = "Atma"

# General Paths

PROJECT_DIRECTORY   =  '/home/varad/MALTA_Restructured/'
DATA_DIRECTORY      =  os.path.join(PROJECT_DIRECTORY,"data", "")
SOURCE_DIRECTORY    =  os.path.join(PROJECT_DIRECTORY, "source", "")
MODEL_DIRECTORY     =  os.path.join(SOURCE_DIRECTORY, "model", "")
SCRIPTS_DIRECTORY   =  os.path.join(SOURCE_DIRECTORY, "scripts","")
FEATURES_DIRECTORY  =  os.path.join(DATA_DIRECTORY, "features", "")
MODEL_SAVE_DIRECTORY = os.path.join(PROJECT_DIRECTORY,"save_model", "")
RESULT_SAVE_DIRECTORY = os.path.join(PROJECT_DIRECTORY,"save_result", "")


# Data Paths : Add your Dataset paths here 

# Third Party Paths

WORD_EMBEDDING_PATH = os.path.join(DATA_DIRECTORY, "external", "cc.mr.300.bin")

# Paths for Atma Dataset
RAW_DATA_DIRECTORY = os.path.join(DATA_DIRECTORY, "raw", DATASET_NAME, "")
RAW_VIDEOS_DIRECTORY = os.path.join(RAW_DATA_DIRECTORY, "videos", "")
RAW_CAPTIONS_DIRECTORY = os.path.join(RAW_DATA_DIRECTORY, "captions", "")

PROCESSED_DATA_DIRECTORY = os.path.join(DATA_DIRECTORY, "processed", DATASET_NAME, "")
PROCESSED_VIDEOS_DIRECTORY = os.path.join(PROCESSED_DATA_DIRECTORY, "videos", "")
PROCESSED_CAPTIONS_DIRECTORY = os.path.join(PROCESSED_DATA_DIRECTORY, "captions", "")
PROCESSED_AUDIO_DIRECTORY = os.path.join(PROCESSED_DATA_DIRECTORY, "audio", "")
PROCESSED_OUTPUT_DIRECTORY = os.path.join(PROCESSED_DATA_DIRECTORY, "output", "")

# Paths for Features

AUDIO_FEATURES_DIRECTORY = os.path.join(FEATURES_DIRECTORY, DATASET_NAME, "audio_features", "")
VGG_AUDIO_FEATURES_DIRECTORY = os.path.join(AUDIO_FEATURES_DIRECTORY, "vgg","")
MFCC_AUDIO_FEATURES_DIRECTORY = os.path.join(AUDIO_FEATURES_DIRECTORY, "mfcc", "")

VIDEO_FEATURES_DIRECTORY = os.path.join(FEATURES_DIRECTORY, DATASET_NAME, "video_features")
C3D_VIDEO_FEATURES_DIRECTORY = os.path.join(VIDEO_FEATURES_DIRECTORY, "c3d")


#Paths for Output Files

VIDEO_LIST_PATH = os.path.join(PROCESSED_OUTPUT_DIRECTORY, VIDEO_LIST_FILENAME)
ANNOTATION_LIST_PATH = os.path.join(PROCESSED_OUTPUT_DIRECTORY, ANNOTATION_PATH_FILENAME)
AUDIO_FEATURES_H5PY_PATH = os.path.join(PROCESSED_OUTPUT_DIRECTORY, "audio_features_"+AUDIO_FEATURES_TO_USE+".h5py")
VIDEO_FEATURES_H5PY_PATH = os.path.join(C3D_VIDEO_FEATURES_DIRECTORY, C3D_FEATURES_FILENAME)
ANNOTATION_TRAIN_PATH = os.path.join(PROCESSED_OUTPUT_DIRECTORY, ANNOTATION_TRAIN_PATHS_FILENAME)
ANNOTATION_TEST_PATH = os.path.join(PROCESSED_OUTPUT_DIRECTORY, ANNOTATION_TEST_PATHS_FILENAME)
ERROR_FILE_PATH = os.path.join(PROCESSED_OUTPUT_DIRECTORY, ERROR_FILENAME)
ANNOTATION_TRAIN_PARSED_PATH = os.path.join(PROCESSED_OUTPUT_DIRECTORY, ANNOTATION_TRAIN_PARSED_FILENAME)
ANNOTATION_TEST_PARSED_PATH = os.path.join(PROCESSED_OUTPUT_DIRECTORY, ANNOTATION_TEST_PARSED_FILENAME)
MOVIE_LENGTH_FILE_PATH = os.path.join(PROCESSED_OUTPUT_DIRECTORY, MOVIE_LENGTH_FILENAME)
LABEL_DIRECTORY = os.path.join(PROCESSED_OUTPUT_DIRECTORY, LABEL_FOLDERNAME, "")
FULL_SPLIT_DATASET_PATH = os.path.join(PROCESSED_OUTPUT_DIRECTORY, FULL_SPLIT_DATASET_FILENAME)
SMALL_SPLIT_DATASET_PATH = os.path.join(PROCESSED_OUTPUT_DIRECTORY, SMALL_SPLIT_DATASET_FILENAME)

CONT_DIRECTORY = os.path.join(PROCESSED_OUTPUT_DIRECTORY, CONT_DIRECTORY_NAME,"")
CONT_CAPTIONS_DIRECTORY = os.path.join(PROCESSED_OUTPUT_DIRECTORY, CONT_CAPTIONS_DIRECTORY_NAME, "")

